name: checkout
description: |
  Fetches the content of the current repo without relying on Node.js and its machinery.
author: KOLANICH

inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
    default: ${{ github.sha }}
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: ''
  fetch-depth:
    description: 'Number of commits to fetch.'
    default: 50
  submodules:
    description: >
      Whether to checkout submodules: `true` to checkout submodules or `recursive` to
      recursively checkout submodules.
      When the `ssh-key` input is not provided, SSH URLs beginning with `git@github.com:` are
      converted to HTTPS.
    default: false

runs:
  using: "composite"
  steps:
    - run: bash ${{github.action_path}}/action.sh ${{inputs.repository}} ${{inputs.ref}} "${{inputs.path}}" ${{inputs.fetch-depth}} ${{inputs.submodules}}
      shell: bash  # fuck, this doesn't guarantee that the script is called with bash. Has to call bash explicitly

branding:
  icon: arrow-down-circle
  color: green
